[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "lgtm"
version = "0.1.0"
requires-python = "==3.10.14"
dependencies = [
    "matplotlib==3.10.8",
    "numpy==2.2.6",
    "pandas==2.3.3",
    "scikit-learn==1.7.1",
    "scipy==1.15.2",
    "seaborn==0.13.2",
    "streamlit==1.54.0",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torchvision==0.21.0",
    "tqdm==4.67.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/lgtm"]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchaudio = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
